backend:
  name: github
  repo: tstachl/website
  branch: master
publish_mode: editorial_workflow
media_folder: "public/assets"
public_folder: "/assets"
collections:
  - name: "authors"
    label: "Authors"
    folder: "src/pages/authors"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "../../layouts/Author.astro"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Photo"
        name: "photo"
        widget: image
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "categories"
    label: "Categories"
    folder: "src/pages/categories"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "../../layouts/Category.astro"
      - label: "Title"
        name: "title"
        widget: "string"
  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "../../layouts/BlogPost.astro"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["title"]
        value_field: "{{slug}}.md"
        display_fields: ["title"]
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Banner"
        name: "banner"
        widget: "list"
        summary: '{{fields.image}}'
        field:
          label: Image
          name: image
          widget: image
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        search_fields: ["title"]
        value_field: "{{title}}"
        display_fields: ["title"]
      - label: "Body"
        name: "body"
        widget: "markdown"