backend:
  name: github
  repo: tstachl/website
  branch: master
publish_mode: editorial_workflow
media_folder: "public/assets"
public_folder: "/assets"
collections:
  - name: "posts"
    label: "Post"
    folder: "src/pages/posts"
    create: true
    slug: "{{slug}}"
    editor: preview: false
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "../../layouts/BlogPost.astro"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Banner"
        name: "banner"
        widget: "list"
        summary: '{{fields.image}}'
        field:
          label: Image
          name: image
          widget: image
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Lifestyle"]
      - label: "Body"
        name: "body"
        widget: "markdown"